language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq -d update

install:
  - sudo apt-get install cmake g++-4.8 clang
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - g++ --version

script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" ..
  - make
